# Generated by Django 4.1 on 2022-09-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwitterToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("oauth_verifier", models.CharField(max_length=150)),
                ("oauth_token", models.CharField(max_length=150)),
                ("oauth_token_secret", models.CharField(max_length=150)),
                ("access_token", models.CharField(max_length=100)),
                ("access_token_secret", models.CharField(max_length=100)),
            ],
        ),
    ]
