# Generated by Django 4.1 on 2022-09-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="twittertoken", name="oauth_token",),
        migrations.RemoveField(model_name="twittertoken", name="oauth_token_secret",),
        migrations.RemoveField(model_name="twittertoken", name="oauth_verifier",),
    ]
