# Generated by Django 4.1 on 2022-10-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0002_remove_twittertoken_oauth_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=1000)),
                ("friend_count", models.IntegerField()),
                ("count", models.IntegerField()),
            ],
        ),
    ]
