# Generated by Django 4.1 on 2022-10-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0003_taskdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskdata", old_name="count", new_name="progress_count",
        ),
    ]
